CREATE TABLE Perfil (
	id INT PRIMARY KEY,
	nome_perfil VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE Usuario (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	senha_hash VARCHAR(255) NOT NULL,
	matricula VARCHAR(30) NOT NULL UNIQUE,
	id_perfil INT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT fk_usuario_perfil
		FOREIGN KEY (id_perfil)
		REFERENCES Perfil(id)
) ENGINE=InnoDB;

INSERT INTO Perfil (id, nome_perfil) VALUES
(1, 'Aluno'),
(2, 'Professor'),
(3, 'Coordenador'),
(4, 'Administrador');
